# Generated by Django 3.0 on 2019-12-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
